### ISSUE TITLE
nest后端代码疯狂

### ISSUE THREAD

**Issue by ghtx520** [givebest/node-nest-vue-nuxt-cms#12]
### 提示少这少那的

![image](https://github.com/givebest/node-nest-vue-nuxt-cms/assets/47137558/9aedbc11-41ed-49a4-9968-bcf185a3c542)

**Comment by givebest** [comment]
试试 pnpm、yarn，不建议用 cnpm。

**Comment by ghtx520** [comment]
都试了, 你的node版本是多少, 我换了几个版本都不行

**Comment by givebest** [comment]
> 都试了, 你的node版本是多少, 我换了几个版本都不行

v20.10.0
