### ISSUE TITLE
QueryFailedError: Duplicate entry '' for key 'user.PRIMARY'

### ISSUE THREAD

**Issue by ktmswzw** [givebest/node-nest-vue-nuxt-cms#7]
操作步骤:

1、新增数据库
2、server里 执行 yarn install , 然后运行 yarn run start:dev
3、user表主键就被删掉了.奇葩..

**Comment by givebest** [comment]
https://github.com/givebest/node-nest-vue-nuxt-cms/blob/756d486f7045d4f66a26563028e3805acd7bcabf/server/config/config.default.ts


`synchronize: false` 试下
