### ISSUE TITLE
配置的地址和实践连接的mysql地址不同

### ISSUE THREAD

**Issue by melonlly** [givebest/node-nest-vue-nuxt-cms#9]
配置的地址："type":"mysql","host":"sh-cynosdbmysql-grp-jgarzx84.sql.tencentcdb.com","port":21954
启动后连接的地址： ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: Access denied for user 'root'@'27.17.226.205' (using password: YES)
不知道是不是服务的问题，用的腾讯云的数据库
ping sh-cynosdbmysql-grp-jgarzx84.sql.tencentcdb.com 的ip是 124.222.251.11

**Comment by givebest** [comment]
Error: Access denied for user 'root'@'27.17.226.205' (using password: YES)  

这句是不是重点，配置应该是区分环境：server/config。

**Comment by melonlly** [comment]
> 

![image](https://github.com/givebest/node-nest-vue-nuxt-cms/assets/20829213/1c66a0c8-feb0-4f7e-aee9-7a8f1ecd04fd)
我做测试没区分环境

**Comment by melonlly** [comment]
> 

![image](https://github.com/givebest/node-nest-vue-nuxt-cms/assets/20829213/1c66a0c8-feb0-4f7e-aee9-7a8f1ecd04fd)
我做测试没区分环境

**Comment by melonlly** [comment]
> 配置的地址："type":"mysql","host":"sh-cynosdbmysql-grp-jgarzx84.sql.tencentcdb.com","port":21954 启动后连接的地址： ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)... Error: Access denied for user 'root'@'27.17.226.205' (using password: YES) 不知道是不是服务的问题，用的腾讯云的数据库 ping sh-cynosdbmysql-grp-jgarzx84.sql.tencentcdb.com 的ip是 124.222.251.11

我发现问题了，27.17.226.205这是我本机ip，因为我放到服务器运行，也是连的本机ip，这是为什么？
